# Generated by Django 4.1.4 on 2023-02-08 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('insurance_details', models.CharField(max_length=55)),
                ('room_charge', models.PositiveIntegerField()),
                ('medicine_cost', models.PositiveIntegerField()),
                ('doctor_fee', models.PositiveIntegerField()),
                ('other_charges', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patientmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
